---
SESSION_MIN_TRIALS: 5                 # How many trials does one session have to have in order to be included in the analysis. -> > SESSION_MIN_TRIALS
MICE_LIST:                            # List the mice you want to analyse
  - J011
  - J013
  - J015
  - J016
<<<<<<< HEAD
  - J017
MICE_OPTIMAL_WEIGHT_LOSS: -0.15 # decimal
=======
  - J017
>>>>>>> a3e9c9021f8da0094965fe8220a710ac4554d6fd
